version: '3.5'
services:
  nginx:
    image: ${VENDORNAME}/${PROJECTNAME}/nginx:dev
    container_name: ${PROJECTNAME}_nginx
    volumes:
      - ./../../code/public:/var/www/html/public
    ports:
      - '80:80'

  php:
    image: ${VENDORNAME}/${PROJECTNAME}/php:dev
    container_name: ${PROJECTNAME}_php
    volumes:
      - ./../../code:/var/www/html
      - ./../php/php-ini-overrides.ini:/etc/php/8.0/cli/conf.d/php-ini-overrides.ini

  database:
    image: ${VENDORNAME}/${PROJECTNAME}/database:dev
    container_name: ${PROJECTNAME}_database
    volumes:
      - ./../../database:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'