version: '3.5'
services:
  php_cli:
    image: af.flyeralarm/new_project/php_cli:dev
    working_dir: /var/www/html
    volumes:
      - ./../../code:/var/www/html
      - ./../php_cli/php-ini-overrides.ini:/etc/php/8.0/cli/conf.d/php-ini-overrides.ini
    environment:
      - VHOST=localhost
