version: '3.5'
services:
  nginx:
    image: af.flyeralarm/new_project/nginx:dev
    volumes:
      - ./../../code/public:/var/www/html/public
    ports:
      - '80:80'

  php:
    image: af.flyeralarm/new_project/php:dev
    volumes:
      - ./../../code:/var/www/html
      - ./../php/php-ini-overrides.ini:/etc/php/8.0/cli/conf.d/php-ini-overrides.ini

  database:
    image: af.flyeralarm/new_project/database:dev
    volumes:
      - ./../../database:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'