create table customers
(
    customer_id int auto_increment
        primary key,
    email       varchar(100) null,
    firstname   varchar(60)  null,
    lastname    varchar(60)  null,
    street      varchar(100) null,
    zipcode     varchar(10)  null,
    city        varchar(60)  null,
    state       varchar(60)  null,
    country     varchar(60)  null,
    phone       varchar(25)  null,
    company     varchar(100) null,
    constraint customers_customer_id_uindex
        unique (customer_id)
);

INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (37, 'wildebeugersolmecke@blabla.de', 'Herr', 'Solmecke', 'Law-Street 01', '11111', 'Bern', 'Keine Ahnung', 'Schweiz', '022140067550', 'Kanzlei WBS');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (38, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (39, 'francis@gmail.com', 'Francis', 'De Retardo', 'Staßehalt 93', '41214', 'Björn', 'Bayerm', 'Deutschland', '031231445', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (40, 'colorado.boy@swag.gov', 'Arnold', 'Schwarzeneger', 'Almstraße 1012', '4578', 'Wien', 'Wienerland', 'Österreich', '0101212145', 'USA');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (41, 'moneyboy@moneyboy.at', 'Sebastian', 'Meisinger', 'Meisingerstreet 21', '3246', 'Wien', 'Wienerland', 'Österreich', '01671341456', '21 Entertaintment');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (42, 'billigmann@cheap.de', 'Sven', 'Billigmann', 'Sevensvenson 7', '99954', 'Svenstadt', 'Rheinland-Pfalz', 'Deutschland', '0323456778', 'BM');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (43, 'posterboy@live.de', 'Pete', 'Posterboy', 'Paganstr. 9', '12345', 'Panke', 'Berlin', 'Deutschland', '013557997', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (44, 'RichSwagMafia069@googlemail.com', 'Peter', 'Schmidt', 'Harzstraße 56', '34547', 'Harz', 'Bremen', 'Deutschland', '015547646', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (45, 'irgendjemandhalt@live.de', 'Namenloser', 'Typ', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (46, 'wildebeugersolmecke@blabla.de', 'Herr', 'Solmecke', 'Law-Street 01', '11111', 'Bern', 'Keine Ahnung', 'Schweiz', '022140067550', 'Kanzlei WBS');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (47, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (48, 'wildebeugersolmecke@blabla.de', 'Herr', 'Solmecke', 'Law-Street 01', '11111', 'Bern', 'Keine Ahnung', 'Deutschland', '022140067550', 'Kanzlei WBS');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (49, 'nichtwildebeugersolmecke@blabla.de', 'Frau', 'Solmecke', 'Law-Street 45', '21111', 'Fern', 'Keine Ahnung', 'Österreich', '022140067550', 'Nicht Kanzlei WBS');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (50, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Berlin', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (51, 'wildebeugersolmecke@blabla.de', 'Herr', 'Solmecke', 'Law-Street 01', '11111', 'Bern', 'Keine Ahnung', 'Schweiz', '022140067550', 'Kanzlei WBS');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (52, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (53, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Österreich', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (54, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (55, 'wildebeugersolmecke@blabla.de', 'Herr', 'Solmecke', 'Law-Street 01', '11111', 'Bern', 'Keine Ahnung', 'Schweiz', '022140067550', 'Kanzlei WBS');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (56, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Schweiz', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (57, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Schweiz', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (58, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (59, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (60, 'wildebeugersolmecke@blabla.de', 'Herr', 'Solmecke', 'Law-Street 01', '11111', 'Bern', 'Keine Ahnung', 'Deutschland', '022140067550', 'Kanzlei WBS');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (61, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (62, 'wildebeugersolmecke@blabla.de', 'Herr', 'Solmecke', 'Law-Street 01', '11111', 'Bern', 'Keine Ahnung', 'Deutschland', '022140067550', 'Kanzlei WBS');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (63, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (64, 'wildebeugersolmecke@blabla.de', 'Herr', 'Solmecke', 'Law-Street 01', '11111', 'Bern', 'Keine Ahnung', 'Deutschland', '022140067550', 'Kanzlei WBS');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (65, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (66, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (67, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (68, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (69, 'wildebeugersolmecke@blabla.de', 'Herr', 'Solmecke', 'Law-Street 01', '11111', 'Bern', 'Keine Ahnung', 'Deutschland', '022140067550', 'Kanzlei WBS');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (70, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (71, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (72, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (73, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (74, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (75, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (76, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (77, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (78, 'wildebeugersolmecke@blabla.de', 'Herr', 'Solmecke', 'Law-Street 01', '11111', 'Bern', 'Keine Ahnung', 'Österreich', '022140067550', 'Kanzlei WBS');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (79, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (80, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Österreich', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (81, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (82, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (83, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (84, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (85, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Österreich', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (86, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (87, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (88, 'wildebeugersolmecke@blabla.de', 'Herr', 'Solmecke', 'Law-Street 01', '11111', 'Bern', 'Keine Ahnung', 'Österreich', '022140067550', 'Kanzlei WBS');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (89, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
INSERT INTO webshop.customers (customer_id, email, firstname, lastname, street, zipcode, city, state, country, phone, company) VALUES (90, 'peter.lustig@live.de', 'Peter', 'Lustig', 'Swagstreet 41', '11245', 'Swagcity', 'Brandenburg', 'Deutschland', '01671341456', 'keine');
